services: 
 appservice: 
    container_name: devops-cont 
    build: ./Docker-app 
    ports: 
       - "1111:80" 
    volumes: 
       - appvolume:./Devops-app 
    networks: 
       - appnetwork 
       - dbnetwork
 dbservice:
    container_name: devops-db-cont 
    build: ./Docker-db 
    ports: 
       - "2222:80" 
    volumes: 
       - dbvolume:./Devops-db 
    networks: 
        - dbnetwork 
        - appnetwork
volumes: 
  appvolume: 
  dbvolume:
networks: 
  appnetwork: 
    driver: bridge 
  dbnetwork: 
    driver: bridge
 
