services: 
 appservice: 
    container_name: devops-cont 
    build: ./Devops-app 
    ports: 
       - "1111:80" 
    volumes: 
       - appvolume:./Devops-app 
    network: 
       -appnetwork 
       -dbnetwork
 dbservice:
    container_name: devops-db-cont 
    build: ./Devops-db 
    ports: 
       - "2222:80" 
    volumes: 
       - dbvolume:./Devops-db 
    network: 
        -dbnetwork 
        -appnetwork
volumes: 
  appvolume: 
  dbvolume:
networks: 
  appnetwork: 
    driver: bridge 
  dbnetwork: 
    driver: bridge
 
